homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 144
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Minsk
  # Customization file
  customize: !include customize.yaml

device_tracker:
  - platform: tplink
    host: 192.168.0.1
    username: !secret tplink_router_login
    password: !secret tplink_router_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no

xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_gateway_key

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:65:C5:B7'
    name: Murraya
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/locallost.pro/cert.pem | awk '{ print $NF }'"
  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "111{{ states.sun.sun.attributes.elevation }}111"
      template_last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states.binary_sensor.motion_sensor_158d00015486df] %}
          {% for sensor in sensors %}
            {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
              {{ sensor }}
            {% endif %}
          {% endfor %}
      sunrise:
        value_template: "11{{ states.sun.sun.attributes.next_rising }}11"
  - platform: history_stats
    name: Lamp ON today
    entity_id: binary_sensor.motion_sensor_158d00015486df
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_api_key

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Configuration for web interface
http: !include deps/http.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery: !include deps/discovery.yaml

# Enables support for tracking state changes over time
history: !include deps/history.yaml

# Enables support for tracking state changes over time
recorder: !include deps/recorder.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

group: !include_dir_merge_named groups/

automation: !include_dir_merge_named automations/

script: !include scripts.yaml
