homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 144
  unit_system: metric
  time_zone: Europe/Minsk
  # Customization file
  customize: !include deps/homeassistant/customize.yaml
  customize_glob: !include deps/homeassistant/custom_ui.yaml


xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_gateway_key

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_api_key

customizer:
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index


# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/


# Enables configuration UI
config:
# Checks for available updates
updater:
# View all events in a logbook
logbook:
# Enables a map showing the location of tracked devices
map:
# Track the sun
sun:


# Configuration for web interface
http: !include deps/http.yaml
# Enables support for tracking state changes over time
history: !include deps/history.yaml
# Enables support for tracking state changes over time
recorder: !include deps/recorder.yaml
# Custom sensor configurations
sensor: !include deps/sensor.yaml
# Discover some devices automatically
discovery: !include deps/discovery.yaml
# Notifications (html5/etc)
notify: !include deps/notify.yaml
# MQTT private server config
mqtt: !include deps/mqtt.yaml
# Groups config
group: !include_dir_merge_named groups/
# Home automation
automation: !include_dir_merge_list automations/
# Custom scripts
script: !include deps/scripts.yaml
# Sidebar panels iframe
panel_iframe: !include deps/panel_iframe.yaml
# Device tracker configuration
device_tracker: !include deps/device_tracker.yaml
