version: '3.3'

networks:
  proxy:
    external: true

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:alpine
    restart: always
    command: --web --docker --docker.domain=${MAIN_DOMAIN}
    networks:
      - proxy
    ports:
      - 8090:8080
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/rules.toml:/rules.toml
      - ./traefik/acme.json:/acme.json

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
      - '0.0.0.0:8053:80/tcp'
    environment:
      ServerIP: ${HOST_IP}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.${MAIN_DOMAIN}
      VIRTUAL_PORT: 80
    volumes:
      - ./pihole:/etc/pihole/
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - 'pihole.${MAIN_DOMAIN}:${HOST_IP}'
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.backend=pihole"
      - "traefik.frontend.rule=HostRegexp:pihole.${MAIN_DOMAIN},{catchall:.*}"
      - "traefik.frontend.priority=1"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"

  homeassistant:
    container_name: home-assistant
    restart: always
    image: homeassistant/raspberrypi3-homeassistant
    depends_on:
      - "reverse-proxy"
#    networks:
#      - proxy
    network_mode: host
    ports:
      - ${HA_PORT}:${HA_PORT}
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    extra_hosts:
      - 'ha.${MAIN_DOMAIN}:${HOST_IP}'
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      - "traefik.backend=home-assistant"
#      - "traefik.frontend.rule=Host:ha.${MAIN_DOMAIN}"
#      - "traefik.port=${HA_PORT}"
#      - "traefik.default.protocol=http"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.entryPoints=http,https"

#version: '3.3'
#services:
##  pihole:
##    image: pihole/pihole:latest
##    ports:
##      - "53:53/tcp"
##      - "53:53/udp"
##      - "80:80/tcp"
##      - "443:443/tcp"
##    #cap_add:
##    #  - NET_ADMIN
##    # required if Pi-hole is to provide DHCP
##    # network_mode: "host"
##    environment:
#      ServerIP: ${HOST_IP}
#      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
#      PROXY_LOCATION: pihole
#      VIRTUAL_HOST: pihole.${MAIN_DOMAIN}
#      VIRTUAL_PORT: 80
#    extra_hosts:
#      - 'pihole.${MAIN_DOMAIN}:${HOST_IP}'
##    restart: always
#
#  homeassistant:
#    container_name: home-assistant
#    image: homeassistant/raspberrypi3-homeassistant
#    volumes:
#      - ./:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 8123:8123
#    devices:
#      - /dev/ttyS0:/dev/ttyS0
#      #- /dev/ttyUSB1:/dev/ttyUSB1
#      #- /dev/ttyACM0:/dev/ttyACM0
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=192.168.0.170"
#      - "traefik.docker.network=traefik-public"
#      - "traefik.frontend.rule=Host:ha.${MAIN_DOMAIN}"
#      - "traefik.port=8123"
#      - "traefik.default.protocol=https"
#    restart: always
#    network_mode: host
