- platform: miflora
  mac: 'C4:7C:8D:65:C5:B7'
  name: Murraya
  force_update: false
  median: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: mhz19
  name: Kitchen CO2
  serial_device: /dev/ttyS0
  monitored_conditions:
    - co2
    - temperature
