############################################################
# Humidifiers automation config
############################################################

- alias: Bedroom Humidity Trigger On
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidity_158d00019d3038
      below: 40
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '07:00:00'
      - condition: template
        value_template: "{ states.fan.xiaomi_miio_device.state == 'off' }}"
  action:
    service: homeassistant.turn_on
    entity_id: fan.xiaomi_miio_device

- alias: Bedroom Humidity Trigger Off
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidity_158d00019d3038
      above: 40
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:01:00'
        before: '20:59:00'
      - condition: numeric_state
        entity_id: sensor.humidity
        above: 40
      - condition: template
        value_template: "{{ states.fan.xiaomi_miio_device.state == 'on' }}"
  action:
    service: homeassistant.turn_off
    entity_id: fan.xiaomi_miio_device