flower_muraya:
  view: no
  name: Murraya Flower
  entities:
    - sensor.murraya_moisture
    - sensor.murraya_light_intensity
    - sensor.murraya_temperature
    - sensor.murraya_conductivity
    - sensor.murraya_battery
